### ISSUE TITLE
JRE 11 and Tomcat 9

### ISSUE THREAD

**Issue by mattenp** [OpenNRW/inspire-dcat-de-bridge#12]
Hi,

how can the software run under JRE 11 and Tomcat 9? Are the adaptations difficult or is there already a Maven project?
The software can not run forever under JRE 8.
We now have CKAN running under JRE 11.

Best regards,
Matthias

**Comment by jvanzadelhoff** [comment]
Hi Matthias,

we are currently planning an update that will also entail updating the Java version. The planned timeline for this is Q4 21 / Q1 22.

Best Regards,

Jan

**Comment by mattenp** [comment]
Hi jan,

good news, thanks.


Best regards,

Matthias

**Comment by jvanzadelhoff** [comment]
Hi Matthias,

with the 2.0.0 update the bridge now runs under Java 11 and Tomcat 9

Best Regards,

Jan
