### ISSUE TITLE
nonProxyHosts is not recognized

### ISSUE THREAD

**Issue by kristiansenkler** [OpenNRW/inspire-dcat-de-bridge#13]
Hi all, 

It looks like proxy settings are not completely recognised by the application. The (possible) reason for this is that the Apache HTTPClient 3x is used. It cannot deal with http.nonProxyHosts (and also not with https.proxy* settings).

This can be seen in the classes HostConfiguration and ProxyHost, which only support HostName and Port, but no other proxy parameters. 

(Maybe there is a configuration I haven't found yet that can enable nonProxyHosts? )

Migrating to org.apache.camel:camel-http4 would definitely help, as the HTTPClient 4x used there enforces these proxy settings reasonably.

Is this planned in the near future?

Kind regards,
Kristian

**Comment by jvanzadelhoff** [comment]
Hi Kristian,

we are currently planning an update that should also address the problem you describe. The planned timeline for this is Q4 21 / Q1 22.

Best Regards,

Jan

**Comment by jvanzadelhoff** [comment]
Hi Kristian,

with version 2.0.0 the proxy behaviour can now be configured using the system properties:

```
http.proxyHost
http.proxyPort
http.nonProxyHosts
```

Best Regards,

Jan
